# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84538b8c5cba30a9eaaacff787aa6c7e8005c3db435a84752e5c1db0bdda6eba61dd6a4a4174d991ed857f8aebe1c125503e38fb16bc5295241c6540c1d42d5e

test:
  secret_key_base: 560044fc621a0ebcc93fd5e146dc254f52264d7c09ddba4633f584513c74efef90c38ec2388bd4417a2570ee2306b5339c323f30e0a5d1a126aa5f49a34d0051

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
